name: Build Sileo Repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev gzip

      - name: Generate Packages
        run: |
          dpkg-scanpackages -m debs /dev/null > Packages
          gzip -c9 Packages > Packages.gz

      - name: Generate Release
        run: |
          cat > Release <<EOF
          Origin: OVO-2001 Repo
          Label: OVO-2001 Repo
          Suite: stable
          Version: 1.0
          Codename: ios
          Architectures: iphoneos-arm iphoneos-arm64
          Components: main
          Description: OVO-2001 Sileo Repository
          EOF

      - name: Commit repo files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Packages Packages.gz Release
          git commit -m "Auto update Packages" || echo "No changes"
          git push
